-- US universe seed: ~100 well-known S&P 500 + NASDAQ 100 mega-caps.
-- Used by the 2026 YTD price-bars backfill so price_bars_daily has real data
-- without a separate ticker-roster ingestion pipeline. Idempotent — run any time.

insert into public.instruments (symbol, name, exchange, asset_type, country_code, currency, sector) values
  ('AAPL',  'Apple Inc.',                 'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('MSFT',  'Microsoft Corporation',      'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('NVDA',  'NVIDIA Corporation',         'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('GOOGL', 'Alphabet Inc. Class A',      'NASDAQ',  'stock', 'US', 'USD', 'Communication Services'),
  ('GOOG',  'Alphabet Inc. Class C',      'NASDAQ',  'stock', 'US', 'USD', 'Communication Services'),
  ('AMZN',  'Amazon.com, Inc.',           'NASDAQ',  'stock', 'US', 'USD', 'Consumer Discretionary'),
  ('META',  'Meta Platforms, Inc.',       'NASDAQ',  'stock', 'US', 'USD', 'Communication Services'),
  ('TSLA',  'Tesla, Inc.',                'NASDAQ',  'stock', 'US', 'USD', 'Consumer Discretionary'),
  ('BRK.B', 'Berkshire Hathaway Inc.',    'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('AVGO',  'Broadcom Inc.',              'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('JPM',   'JPMorgan Chase & Co.',       'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('LLY',   'Eli Lilly and Company',      'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('V',     'Visa Inc.',                  'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('XOM',   'Exxon Mobil Corporation',    'NYSE',    'stock', 'US', 'USD', 'Energy'),
  ('UNH',   'UnitedHealth Group Inc.',    'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('MA',    'Mastercard Incorporated',    'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('PG',    'Procter & Gamble Co.',       'NYSE',    'stock', 'US', 'USD', 'Consumer Staples'),
  ('JNJ',   'Johnson & Johnson',          'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('HD',    'The Home Depot, Inc.',       'NYSE',    'stock', 'US', 'USD', 'Consumer Discretionary'),
  ('COST',  'Costco Wholesale Corp.',     'NASDAQ',  'stock', 'US', 'USD', 'Consumer Staples'),
  ('ABBV',  'AbbVie Inc.',                'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('MRK',   'Merck & Co., Inc.',          'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('CVX',   'Chevron Corporation',        'NYSE',    'stock', 'US', 'USD', 'Energy'),
  ('NFLX',  'Netflix, Inc.',              'NASDAQ',  'stock', 'US', 'USD', 'Communication Services'),
  ('AMD',   'Advanced Micro Devices',     'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('WMT',   'Walmart Inc.',               'NYSE',    'stock', 'US', 'USD', 'Consumer Staples'),
  ('PEP',   'PepsiCo, Inc.',              'NASDAQ',  'stock', 'US', 'USD', 'Consumer Staples'),
  ('KO',    'The Coca-Cola Company',      'NYSE',    'stock', 'US', 'USD', 'Consumer Staples'),
  ('ADBE',  'Adobe Inc.',                 'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('CRM',   'Salesforce, Inc.',           'NYSE',    'stock', 'US', 'USD', 'Information Technology'),
  ('BAC',   'Bank of America Corp.',      'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('TMO',   'Thermo Fisher Scientific',   'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('LIN',   'Linde plc',                  'NASDAQ',  'stock', 'US', 'USD', 'Materials'),
  ('ACN',   'Accenture plc',              'NYSE',    'stock', 'US', 'USD', 'Information Technology'),
  ('MCD',   'McDonald''s Corporation',    'NYSE',    'stock', 'US', 'USD', 'Consumer Discretionary'),
  ('CSCO',  'Cisco Systems, Inc.',        'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('ABT',   'Abbott Laboratories',        'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('DHR',   'Danaher Corporation',        'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('WFC',   'Wells Fargo & Company',      'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('TXN',   'Texas Instruments Inc.',     'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('INTC',  'Intel Corporation',          'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('CMCSA', 'Comcast Corporation',        'NASDAQ',  'stock', 'US', 'USD', 'Communication Services'),
  ('VZ',    'Verizon Communications',     'NYSE',    'stock', 'US', 'USD', 'Communication Services'),
  ('NKE',   'NIKE, Inc.',                 'NYSE',    'stock', 'US', 'USD', 'Consumer Discretionary'),
  ('PM',    'Philip Morris International','NYSE',    'stock', 'US', 'USD', 'Consumer Staples'),
  ('DIS',   'The Walt Disney Company',    'NYSE',    'stock', 'US', 'USD', 'Communication Services'),
  ('NEE',   'NextEra Energy, Inc.',       'NYSE',    'stock', 'US', 'USD', 'Utilities'),
  ('UNP',   'Union Pacific Corporation',  'NYSE',    'stock', 'US', 'USD', 'Industrials'),
  ('PFE',   'Pfizer Inc.',                'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('T',     'AT&T Inc.',                  'NYSE',    'stock', 'US', 'USD', 'Communication Services'),
  ('AMGN',  'Amgen Inc.',                 'NASDAQ',  'stock', 'US', 'USD', 'Health Care'),
  ('IBM',   'International Business Machines', 'NYSE','stock','US','USD','Information Technology'),
  ('ORCL',  'Oracle Corporation',         'NYSE',    'stock', 'US', 'USD', 'Information Technology'),
  ('HON',   'Honeywell International',    'NASDAQ',  'stock', 'US', 'USD', 'Industrials'),
  ('COP',   'ConocoPhillips',             'NYSE',    'stock', 'US', 'USD', 'Energy'),
  ('LOW',   'Lowe''s Companies, Inc.',    'NYSE',    'stock', 'US', 'USD', 'Consumer Discretionary'),
  ('GS',    'The Goldman Sachs Group',    'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('SBUX',  'Starbucks Corporation',      'NASDAQ',  'stock', 'US', 'USD', 'Consumer Discretionary'),
  ('CAT',   'Caterpillar Inc.',           'NYSE',    'stock', 'US', 'USD', 'Industrials'),
  ('MS',    'Morgan Stanley',             'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('AXP',   'American Express Company',   'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('BLK',   'BlackRock, Inc.',            'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('GE',    'General Electric Company',   'NYSE',    'stock', 'US', 'USD', 'Industrials'),
  ('ELV',   'Elevance Health, Inc.',      'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('SCHW',  'The Charles Schwab Corp.',   'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('PLD',   'Prologis, Inc.',             'NYSE',    'stock', 'US', 'USD', 'Real Estate'),
  ('LMT',   'Lockheed Martin Corp.',      'NYSE',    'stock', 'US', 'USD', 'Industrials'),
  ('DE',    'Deere & Company',            'NYSE',    'stock', 'US', 'USD', 'Industrials'),
  ('SYK',   'Stryker Corporation',        'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('TMUS',  'T-Mobile US, Inc.',          'NASDAQ',  'stock', 'US', 'USD', 'Communication Services'),
  ('BKNG',  'Booking Holdings Inc.',      'NASDAQ',  'stock', 'US', 'USD', 'Consumer Discretionary'),
  ('SPGI',  'S&P Global Inc.',            'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('GILD',  'Gilead Sciences, Inc.',      'NASDAQ',  'stock', 'US', 'USD', 'Health Care'),
  ('ISRG',  'Intuitive Surgical, Inc.',   'NASDAQ',  'stock', 'US', 'USD', 'Health Care'),
  ('VRTX',  'Vertex Pharmaceuticals',     'NASDAQ',  'stock', 'US', 'USD', 'Health Care'),
  ('ADP',   'Automatic Data Processing',  'NASDAQ',  'stock', 'US', 'USD', 'Industrials'),
  ('REGN',  'Regeneron Pharmaceuticals',  'NASDAQ',  'stock', 'US', 'USD', 'Health Care'),
  ('CB',    'Chubb Limited',              'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('MMC',   'Marsh & McLennan Companies', 'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('PANW',  'Palo Alto Networks',         'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('QCOM',  'QUALCOMM Incorporated',      'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('MDLZ',  'Mondelez International',     'NASDAQ',  'stock', 'US', 'USD', 'Consumer Staples'),
  ('SO',    'The Southern Company',       'NYSE',    'stock', 'US', 'USD', 'Utilities'),
  ('DUK',   'Duke Energy Corporation',    'NYSE',    'stock', 'US', 'USD', 'Utilities'),
  ('ZTS',   'Zoetis Inc.',                'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('CL',    'Colgate-Palmolive Company',  'NYSE',    'stock', 'US', 'USD', 'Consumer Staples'),
  ('CI',    'Cigna Group',                'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('BSX',   'Boston Scientific Corp.',    'NYSE',    'stock', 'US', 'USD', 'Health Care'),
  ('USB',   'U.S. Bancorp',               'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('PNC',   'The PNC Financial Services', 'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('AMAT',  'Applied Materials, Inc.',    'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('PYPL',  'PayPal Holdings, Inc.',      'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('SHW',   'The Sherwin-Williams Co.',   'NYSE',    'stock', 'US', 'USD', 'Materials'),
  ('NOW',   'ServiceNow, Inc.',           'NYSE',    'stock', 'US', 'USD', 'Information Technology'),
  ('UPS',   'United Parcel Service',      'NYSE',    'stock', 'US', 'USD', 'Industrials'),
  ('TJX',   'The TJX Companies, Inc.',    'NYSE',    'stock', 'US', 'USD', 'Consumer Discretionary'),
  ('MO',    'Altria Group, Inc.',         'NYSE',    'stock', 'US', 'USD', 'Consumer Staples'),
  ('INTU',  'Intuit Inc.',                'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('ICE',   'Intercontinental Exchange',  'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('CME',   'CME Group Inc.',             'NASDAQ',  'stock', 'US', 'USD', 'Financials'),
  ('EQIX',  'Equinix, Inc.',              'NASDAQ',  'stock', 'US', 'USD', 'Real Estate'),
  ('FI',    'Fiserv, Inc.',               'NYSE',    'stock', 'US', 'USD', 'Financials'),
  ('MU',    'Micron Technology, Inc.',    'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('LRCX',  'Lam Research Corporation',   'NASDAQ',  'stock', 'US', 'USD', 'Information Technology'),
  ('SPY',   'SPDR S&P 500 ETF Trust',     'NYSEARCA','etf',   'US', 'USD', 'ETF'),
  ('QQQ',   'Invesco QQQ Trust',          'NASDAQ',  'etf',   'US', 'USD', 'ETF')
on conflict (symbol, exchange) do update
set
  name = excluded.name,
  asset_type = excluded.asset_type,
  country_code = excluded.country_code,
  currency = excluded.currency,
  sector = excluded.sector,
  is_active = true;
